[package]
name = "momentum"
version = "0.1.0"
edition = "2024"

[dependencies]
bincode = "2.0.1"
eframe = "0.31.1"
egui = "0.31.1"
egui-macroquad = "0.17.3"
macroquad = "0.4.14"
rand = "0.9.1"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
